package b4j.example;


import anywheresoftware.b4a.BA;

public class modchartkick extends Object{
public static modchartkick mostCurrent = new modchartkick();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modchartkick", null);
		ba.loadHtSubs(modchartkick.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modchartkick", ba);
		}
	}
    public static Class<?> getObject() {
		return modchartkick.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static b4j.example.bananovm _vm = null;
public static String _name = "";
public static b4j.example.main _main = null;
public static b4j.example.modfile _modfile = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.modgmap _modgmap = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbadge _modbadge = null;
public static b4j.example.modbottombar _modbottombar = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modemptystate _modemptystate = null;
public static b4j.example.modicon _modicon = null;
public static b4j.example.modlist _modlist = null;
public static b4j.example.modlistview _modlistview = null;
public static b4j.example.modmenu _modmenu = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradio _modradio = null;
public static b4j.example.modselect _modselect = null;
public static b4j.example.modskeleton _modskeleton = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modspeeddial _modspeeddial = null;
public static b4j.example.modspinner _modspinner = null;
public static b4j.example.modsteppers _modsteppers = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtable _modtable = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextbox _modtextbox = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtypography _modtypography = null;
public static String  _code(b4j.example.bananovm _vmx) throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmchartkick _provchart = null;
b4j.example.vmchartkick _pie = null;
b4j.example.vmchartkick _colchart = null;
b4j.example.vmchartkick _barchart = null;
b4j.example.vmchartkick _areachart = null;
b4j.example.vmchartkick _scatterchart = null;
b4j.example.vmchartkick _linechartm = null;
b4j.example.vmchartkick _donut = null;
b4j.example.vmchartkick _linechart1 = null;
b4j.example.vmchartkick _colchart1 = null;
b4j.example.vmchartkick _areachart1 = null;
b4j.example.vmchartkick _barchart1 = null;
b4j.example.vmchartkick _colchart2 = null;
b4j.example.vmchartkick _barchart2 = null;
b4j.example.vmchartkick _scatterchart1 = null;
 //BA.debugLineNum = 8;BA.debugLine="Sub Code(vmx As BANanoVM)";
 //BA.debugLineNum = 9;BA.debugLine="Log(\"modChartKick.Code\")";
anywheresoftware.b4a.keywords.Common.Log("modChartKick.Code");
 //BA.debugLineNum = 10;BA.debugLine="vm = vmx";
_vm = _vmx;
 //BA.debugLineNum = 12;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modchartkick.getObject());
 //BA.debugLineNum = 14;BA.debugLine="cont.Hide";
_cont._hide /*String*/ ();
 //BA.debugLineNum = 16;BA.debugLine="cont.AddRows(5).AddColumns4x3";
_cont._addrows /*b4j.example.vmgrid*/ ((int) (5))._addcolumns4x3 /*b4j.example.vmgrid*/ ();
 //BA.debugLineNum = 18;BA.debugLine="Dim provChart As VMChartKick = vm.CreateChartKick";
_provchart = _vm._createchartkick /*b4j.example.vmchartkick*/ ("provChart",modchartkick.getObject())._setlinechart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 19;BA.debugLine="provChart.AddXYMap(CreateMap(\"2013-02-10\":11,\"201";
_provchart._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(11),(Object)("2013-02-11"),(Object)(6),(Object)("2013-02-12"),(Object)(3),(Object)("2013-02-13"),(Object)(2),(Object)("2013-02-14"),(Object)(5),(Object)("2013-02-15"),(Object)(3),(Object)("2013-02-16"),(Object)(8),(Object)("2013-02-17"),(Object)(6),(Object)("2013-02-18"),(Object)(6),(Object)("2013-02-19"),(Object)(12),(Object)("2013-02-20"),(Object)(5),(Object)("2013-02-21"),(Object)(5),(Object)("2013-02-22"),(Object)(3),(Object)("2013-02-23"),(Object)(1),(Object)("2013-02-24"),(Object)(10),(Object)("2013-02-25"),(Object)(1),(Object)("2013-02-26"),(Object)(3),(Object)("2013-02-27"),(Object)(2),(Object)("2013-02-28"),(Object)(3),(Object)("2013-03-01"),(Object)(2),(Object)("2013-03-02"),(Object)(8)}));
 //BA.debugLineNum = 23;BA.debugLine="provChart.SetTitle(\"My Chart\")";
_provchart._settitle /*b4j.example.vmchartkick*/ ("My Chart");
 //BA.debugLineNum = 24;BA.debugLine="cont.AddComponent(1,1, provChart.tostring)";
_cont._addcomponent /*String*/ ((int) (1),(int) (1),_provchart._tostring /*String*/ ());
 //BA.debugLineNum = 26;BA.debugLine="Dim pie As VMChartKick = vm.CreateChartKick(\"pie\"";
_pie = _vm._createchartkick /*b4j.example.vmchartkick*/ ("pie",modchartkick.getObject())._setpiechart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 27;BA.debugLine="pie.AddXYMap(CreateMap(\"Blueberry\":44,\"Strawberry";
_pie._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("Blueberry"),(Object)(44),(Object)("Strawberry"),(Object)(23),(Object)("Banana"),(Object)(22),(Object)("Apple"),(Object)(21),(Object)("Grape"),(Object)(13)}));
 //BA.debugLineNum = 28;BA.debugLine="cont.AddComponent(1,2, pie.tostring)";
_cont._addcomponent /*String*/ ((int) (1),(int) (2),_pie._tostring /*String*/ ());
 //BA.debugLineNum = 30;BA.debugLine="Dim colChart As VMChartKick = vm.CreateChartKick(";
_colchart = _vm._createchartkick /*b4j.example.vmchartkick*/ ("colChart",modchartkick.getObject())._setcolumnchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 31;BA.debugLine="colChart.AddXYMap(CreateMap(\"0\":32,\"1\":46,\"2\":28,";
_colchart._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 32;BA.debugLine="cont.AddComponent(1,3, colChart.tostring)";
_cont._addcomponent /*String*/ ((int) (1),(int) (3),_colchart._tostring /*String*/ ());
 //BA.debugLineNum = 34;BA.debugLine="Dim barChart As VMChartKick = vm.CreateChartKick(";
_barchart = _vm._createchartkick /*b4j.example.vmchartkick*/ ("barChart",modchartkick.getObject())._setbarchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 35;BA.debugLine="barChart.AddXYMap(CreateMap(\"0\":32,\"1\":46,\"2\":28,";
_barchart._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 36;BA.debugLine="cont.AddComponent(1,4, barChart.tostring)";
_cont._addcomponent /*String*/ ((int) (1),(int) (4),_barchart._tostring /*String*/ ());
 //BA.debugLineNum = 38;BA.debugLine="Dim areaChart As VMChartKick = vm.CreateChartKick";
_areachart = _vm._createchartkick /*b4j.example.vmchartkick*/ ("areaChart",modchartkick.getObject())._setareachart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 39;BA.debugLine="areaChart.AddXYMap(CreateMap(\"2013-02-10\":11,\"201";
_areachart._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(11),(Object)("2013-02-11"),(Object)(6),(Object)("2013-02-12"),(Object)(3),(Object)("2013-02-13"),(Object)(2),(Object)("2013-02-14"),(Object)(5),(Object)("2013-02-15"),(Object)(3),(Object)("2013-02-16"),(Object)(8),(Object)("2013-02-17"),(Object)(6),(Object)("2013-02-18"),(Object)(6),(Object)("2013-02-19"),(Object)(12),(Object)("2013-02-20"),(Object)(5),(Object)("2013-02-21"),(Object)(5),(Object)("2013-02-22"),(Object)(3),(Object)("2013-02-23"),(Object)(1),(Object)("2013-02-24"),(Object)(10),(Object)("2013-02-25"),(Object)(1),(Object)("2013-02-26"),(Object)(3),(Object)("2013-02-27"),(Object)(2),(Object)("2013-02-28"),(Object)(3),(Object)("2013-03-01"),(Object)(2),(Object)("2013-03-02"),(Object)(8)}));
 //BA.debugLineNum = 42;BA.debugLine="cont.AddComponent(2,1, areaChart.tostring)";
_cont._addcomponent /*String*/ ((int) (2),(int) (1),_areachart._tostring /*String*/ ());
 //BA.debugLineNum = 44;BA.debugLine="Dim scatterChart As VMChartKick = vm.CreateChartK";
_scatterchart = _vm._createchartkick /*b4j.example.vmchartkick*/ ("scatterChart",modchartkick.getObject())._setscatterchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 45;BA.debugLine="scatterChart.AddXYMap(CreateMap(174.0: 80.0, 176.";
_scatterchart._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)(174.0),(Object)(80.0),(Object)(176.5),(Object)(82.3),(Object)(180.3),(Object)(73.6),(Object)(167.6),(Object)(74.1),(Object)(188.0),(Object)(85.9)}));
 //BA.debugLineNum = 46;BA.debugLine="scatterChart.SetXTitle(\"Size\")";
_scatterchart._setxtitle /*b4j.example.vmchartkick*/ ("Size");
 //BA.debugLineNum = 47;BA.debugLine="scatterChart.SetYTitle(\"Population\")";
_scatterchart._setytitle /*b4j.example.vmchartkick*/ ("Population");
 //BA.debugLineNum = 48;BA.debugLine="cont.AddComponent(2,2, scatterChart.tostring)";
_cont._addcomponent /*String*/ ((int) (2),(int) (2),_scatterchart._tostring /*String*/ ());
 //BA.debugLineNum = 50;BA.debugLine="Dim lineChartM As VMChartKick = vm.CreateChartKic";
_linechartm = _vm._createchartkick /*b4j.example.vmchartkick*/ ("lineChartM",modchartkick.getObject())._setlinechart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 51;BA.debugLine="lineChartM.AddSeries(\"Workout\", \"\", True, CreateM";
_linechartm._addseries /*b4j.example.vmchartkick*/ ("Workout","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(3),(Object)("2013-02-17"),(Object)(3),(Object)("2013-02-24"),(Object)(3),(Object)("2013-03-03"),(Object)(1),(Object)("2013-03-10"),(Object)(4),(Object)("2013-03-17"),(Object)(3),(Object)("2013-03-24"),(Object)(2),(Object)("2013-03-31"),(Object)(3)}));
 //BA.debugLineNum = 52;BA.debugLine="lineChartM.AddSeries(\"Go to concert\", \"\", True, C";
_linechartm._addseries /*b4j.example.vmchartkick*/ ("Go to concert","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(0),(Object)("2013-02-17"),(Object)(0),(Object)("2013-02-24"),(Object)(0),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(2),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(0),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 53;BA.debugLine="lineChartM.AddSeries(\"Wash face\",\"\", True, Create";
_linechartm._addseries /*b4j.example.vmchartkick*/ ("Wash face","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(0),(Object)("2013-02-17"),(Object)(1),(Object)("2013-02-24"),(Object)(0),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(0),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(0),(Object)("2013-03-31"),(Object)(1)}));
 //BA.debugLineNum = 54;BA.debugLine="lineChartM.AddSeries(\"Call parents\",\"\", True, Cre";
_linechartm._addseries /*b4j.example.vmchartkick*/ ("Call parents","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(5),(Object)("2013-02-17"),(Object)(3),(Object)("2013-02-24"),(Object)(2),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(0),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(1),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 55;BA.debugLine="lineChartM.AddSeries(\"Eat breakfast\",\"\",True, Cre";
_linechartm._addseries /*b4j.example.vmchartkick*/ ("Eat breakfast","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(3),(Object)("2013-02-17"),(Object)(2),(Object)("2013-02-24"),(Object)(1),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(2),(Object)("2013-03-17"),(Object)(2),(Object)("2013-03-24"),(Object)(3),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 57;BA.debugLine="cont.AddComponent(2,3, lineChartM.tostring)";
_cont._addcomponent /*String*/ ((int) (2),(int) (3),_linechartm._tostring /*String*/ ());
 //BA.debugLineNum = 59;BA.debugLine="Dim donut As VMChartKick = vm.CreateChartKick(\"do";
_donut = _vm._createchartkick /*b4j.example.vmchartkick*/ ("donut",modchartkick.getObject())._setpiechart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 60;BA.debugLine="donut.AddXYMap(CreateMap(\"Blueberry\":44,\"Strawber";
_donut._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("Blueberry"),(Object)(44),(Object)("Strawberry"),(Object)(23),(Object)("Banana"),(Object)(22),(Object)("Apple"),(Object)(21),(Object)("Grape"),(Object)(13)}));
 //BA.debugLineNum = 61;BA.debugLine="donut.SetDonut";
_donut._setdonut /*b4j.example.vmchartkick*/ ();
 //BA.debugLineNum = 62;BA.debugLine="cont.AddComponent(2,4, donut.tostring)";
_cont._addcomponent /*String*/ ((int) (2),(int) (4),_donut._tostring /*String*/ ());
 //BA.debugLineNum = 64;BA.debugLine="Dim lineChart1 As VMChartKick = vm.CreateChartKic";
_linechart1 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("lineChart1",modchartkick.getObject())._setlinechart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 65;BA.debugLine="lineChart1.AddXYMap(CreateMap(\"Jan\": 4, \"Feb\": 2,";
_linechart1._addxymap /*b4j.example.vmchartkick*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("Jan"),(Object)(4),(Object)("Feb"),(Object)(2),(Object)("Mar"),(Object)(10),(Object)("Apr"),(Object)(5),(Object)("May"),(Object)(3)}));
 //BA.debugLineNum = 66;BA.debugLine="lineChart1.SetCurve";
_linechart1._setcurve /*b4j.example.vmchartkick*/ ();
 //BA.debugLineNum = 67;BA.debugLine="cont.AddComponent(3, 1, lineChart1.tostring)";
_cont._addcomponent /*String*/ ((int) (3),(int) (1),_linechart1._tostring /*String*/ ());
 //BA.debugLineNum = 69;BA.debugLine="Dim colChart1 As VMChartKick = vm.CreateChartKick";
_colchart1 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("colChart1",modchartkick.getObject())._setcolumnchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 70;BA.debugLine="colChart1.AddSeries(\"Series A\", \"\", False, Create";
_colchart1._addseries /*b4j.example.vmchartkick*/ ("Series A","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 71;BA.debugLine="colChart1.AddSeries(\"Series B\", \"\", False, Create";
_colchart1._addseries /*b4j.example.vmchartkick*/ ("Series B","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 72;BA.debugLine="colChart1.SetStacked";
_colchart1._setstacked /*b4j.example.vmchartkick*/ ();
 //BA.debugLineNum = 73;BA.debugLine="cont.AddComponent(3,2, colChart1.tostring)";
_cont._addcomponent /*String*/ ((int) (3),(int) (2),_colchart1._tostring /*String*/ ());
 //BA.debugLineNum = 75;BA.debugLine="Dim areaChart1 As VMChartKick = vm.CreateChartKic";
_areachart1 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("areaChart1",modchartkick.getObject())._setareachart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 76;BA.debugLine="areaChart1.AddSeries(\"Workout\", \"\", True, CreateM";
_areachart1._addseries /*b4j.example.vmchartkick*/ ("Workout","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(3),(Object)("2013-02-17"),(Object)(3),(Object)("2013-02-24"),(Object)(3),(Object)("2013-03-03"),(Object)(1),(Object)("2013-03-10"),(Object)(4),(Object)("2013-03-17"),(Object)(3),(Object)("2013-03-24"),(Object)(2),(Object)("2013-03-31"),(Object)(3)}));
 //BA.debugLineNum = 77;BA.debugLine="areaChart1.AddSeries(\"Go to concert\", \"\", True, C";
_areachart1._addseries /*b4j.example.vmchartkick*/ ("Go to concert","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(0),(Object)("2013-02-17"),(Object)(0),(Object)("2013-02-24"),(Object)(0),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(2),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(0),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 78;BA.debugLine="areaChart1.AddSeries(\"Wash face\",\"\", True, Create";
_areachart1._addseries /*b4j.example.vmchartkick*/ ("Wash face","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(0),(Object)("2013-02-17"),(Object)(1),(Object)("2013-02-24"),(Object)(0),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(0),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(0),(Object)("2013-03-31"),(Object)(1)}));
 //BA.debugLineNum = 79;BA.debugLine="areaChart1.AddSeries(\"Call parents\",\"\", True, Cre";
_areachart1._addseries /*b4j.example.vmchartkick*/ ("Call parents","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(5),(Object)("2013-02-17"),(Object)(3),(Object)("2013-02-24"),(Object)(2),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(0),(Object)("2013-03-17"),(Object)(1),(Object)("2013-03-24"),(Object)(1),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 80;BA.debugLine="areaChart1.AddSeries(\"Eat breakfast\",\"\",True, Cre";
_areachart1._addseries /*b4j.example.vmchartkick*/ ("Eat breakfast","",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("2013-02-10"),(Object)(3),(Object)("2013-02-17"),(Object)(2),(Object)("2013-02-24"),(Object)(1),(Object)("2013-03-03"),(Object)(0),(Object)("2013-03-10"),(Object)(2),(Object)("2013-03-17"),(Object)(2),(Object)("2013-03-24"),(Object)(3),(Object)("2013-03-31"),(Object)(0)}));
 //BA.debugLineNum = 81;BA.debugLine="cont.AddComponent(3,3, areaChart1.tostring)";
_cont._addcomponent /*String*/ ((int) (3),(int) (3),_areachart1._tostring /*String*/ ());
 //BA.debugLineNum = 83;BA.debugLine="Dim barChart1 As VMChartKick = vm.CreateChartKick";
_barchart1 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("barChart1",modchartkick.getObject())._setbarchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 84;BA.debugLine="barChart1.AddSeries(\"Series A\", \"\", False, Create";
_barchart1._addseries /*b4j.example.vmchartkick*/ ("Series A","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 85;BA.debugLine="barChart1.AddSeries(\"Series B\", \"\", False, Create";
_barchart1._addseries /*b4j.example.vmchartkick*/ ("Series B","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 86;BA.debugLine="barChart1.SetMax(80)";
_barchart1._setmax /*b4j.example.vmchartkick*/ ((int) (80));
 //BA.debugLineNum = 87;BA.debugLine="barChart1.SetStacked";
_barchart1._setstacked /*b4j.example.vmchartkick*/ ();
 //BA.debugLineNum = 88;BA.debugLine="cont.AddComponent(3,4, barChart1.tostring)";
_cont._addcomponent /*String*/ ((int) (3),(int) (4),_barchart1._tostring /*String*/ ());
 //BA.debugLineNum = 90;BA.debugLine="Dim colChart2 As VMChartKick = vm.CreateChartKick";
_colchart2 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("colChart2",modchartkick.getObject())._setcolumnchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 91;BA.debugLine="colChart2.AddSeries(\"Series A\", \"\", False, Create";
_colchart2._addseries /*b4j.example.vmchartkick*/ ("Series A","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 92;BA.debugLine="colChart2.AddSeries(\"Series B\", \"\", False, Create";
_colchart2._addseries /*b4j.example.vmchartkick*/ ("Series B","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 93;BA.debugLine="cont.AddComponent(4,1, colChart2.tostring)";
_cont._addcomponent /*String*/ ((int) (4),(int) (1),_colchart2._tostring /*String*/ ());
 //BA.debugLineNum = 95;BA.debugLine="Dim barChart2 As VMChartKick = vm.CreateChartKick";
_barchart2 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("barChart2",modchartkick.getObject())._setbarchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 96;BA.debugLine="barChart2.AddSeries(\"Series A\", \"\", False, Create";
_barchart2._addseries /*b4j.example.vmchartkick*/ ("Series A","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 97;BA.debugLine="barChart2.AddSeries(\"Series B\", \"\", False, Create";
_barchart2._addseries /*b4j.example.vmchartkick*/ ("Series B","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("0"),(Object)(32),(Object)("1"),(Object)(46),(Object)("2"),(Object)(28),(Object)("3"),(Object)(21),(Object)("4"),(Object)(20),(Object)("5"),(Object)(13),(Object)("6"),(Object)(27)}));
 //BA.debugLineNum = 98;BA.debugLine="cont.AddComponent(4,2, barChart2.tostring)";
_cont._addcomponent /*String*/ ((int) (4),(int) (2),_barchart2._tostring /*String*/ ());
 //BA.debugLineNum = 100;BA.debugLine="Dim scatterChart1 As VMChartKick = vm.CreateChart";
_scatterchart1 = _vm._createchartkick /*b4j.example.vmchartkick*/ ("scatterChart1",modchartkick.getObject())._setscatterchart /*b4j.example.vmchartkick*/ ()._setstylesingle /*b4j.example.vmchartkick*/ ("height","300px");
 //BA.debugLineNum = 101;BA.debugLine="scatterChart1.AddSeries(\"Female\", \"\", False, Crea";
_scatterchart1._addseries /*b4j.example.vmchartkick*/ ("Female","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)(174.0),(Object)(73.6),(Object)(162.6),(Object)(61.4),(Object)(174.0),(Object)(55.5),(Object)(162.6),(Object)(63.6),(Object)(161.3),(Object)(60.9)}));
 //BA.debugLineNum = 102;BA.debugLine="scatterChart1.AddSeries(\"Male\", \"\", False, Create";
_scatterchart1._addseries /*b4j.example.vmchartkick*/ ("Male","",anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)(174.0),(Object)(80.0),(Object)(176.5),(Object)(82.3),(Object)(180.3),(Object)(73.6),(Object)(167.6),(Object)(74.1),(Object)(188.0),(Object)(85.9)}));
 //BA.debugLineNum = 103;BA.debugLine="cont.AddComponent(4,3, scatterChart1.tostring)";
_cont._addcomponent /*String*/ ((int) (4),(int) (3),_scatterchart1._tostring /*String*/ ());
 //BA.debugLineNum = 105;BA.debugLine="vm.Container.AddComponent(1,1,cont.tostring)";
_vm._container /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (1),_cont._tostring /*String*/ ());
 //BA.debugLineNum = 106;BA.debugLine="End Sub'Static code module";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 4;BA.debugLine="Public name As String = \"chartkickcode\"";
_name = "chartkickcode";
 //BA.debugLineNum = 5;BA.debugLine="End Sub";
return "";
}
}
