package b4j.example;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class vmcss_subs_0 {


public static RemoteObject  _build(RemoteObject __ref) throws Exception{
try {
		Debug.PushSubsStack("Build (vmcss) ","vmcss",48,__ref.getField(false, "ba"),__ref,80);
if (RapidSub.canDelegate("build")) { return __ref.runUserSub(false, "vmcss","build", __ref);}
RemoteObject _strprop = RemoteObject.createImmutable("");
 BA.debugLineNum = 80;BA.debugLine="Sub Build";
Debug.JustUpdateDeviceLine();
 BA.debugLineNum = 81;BA.debugLine="SetAttr(\"color\",Style.Color)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("color")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"Color" /*RemoteObject*/ )));
 BA.debugLineNum = 82;BA.debugLine="SetAttr(\"text-align\",Text.align)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-align")),(Object)(__ref.getField(false,"_text" /*RemoteObject*/ ).getField(true,"align" /*RemoteObject*/ )));
 BA.debugLineNum = 83;BA.debugLine="SetAttr(\"text-decoration\",Text.decoration)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-decoration")),(Object)(__ref.getField(false,"_text" /*RemoteObject*/ ).getField(true,"decoration" /*RemoteObject*/ )));
 BA.debugLineNum = 84;BA.debugLine="SetAttr(\"text-indent\", Text.indent)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-indent")),(Object)(__ref.getField(false,"_text" /*RemoteObject*/ ).getField(true,"indent" /*RemoteObject*/ )));
 BA.debugLineNum = 85;BA.debugLine="SetAttr(\"letter-spacing\", Style.letterspacing)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("letter-spacing")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"letterspacing" /*RemoteObject*/ )));
 BA.debugLineNum = 86;BA.debugLine="SetAttr(\"line-height\", Style.lineheight)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("line-height")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"lineheight" /*RemoteObject*/ )));
 BA.debugLineNum = 87;BA.debugLine="SetAttr(\"direction\", Style.direction)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("direction")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"direction" /*RemoteObject*/ )));
 BA.debugLineNum = 88;BA.debugLine="SetAttr(\"word-spacing\", Style.wordspacing)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("word-spacing")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"wordspacing" /*RemoteObject*/ )));
 BA.debugLineNum = 89;BA.debugLine="SetAttr(\"text-shadow\", Text.Textshadow)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-shadow")),(Object)(__ref.getField(false,"_text" /*RemoteObject*/ ).getField(true,"Textshadow" /*RemoteObject*/ )));
 BA.debugLineNum = 90;BA.debugLine="SetAttr(\"vertical-align\", Style.verticalalign)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("vertical-align")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"verticalalign" /*RemoteObject*/ )));
 BA.debugLineNum = 91;BA.debugLine="SetAttr(\"display\",Style.display)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("display")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"display" /*RemoteObject*/ )));
 BA.debugLineNum = 92;BA.debugLine="SetAttr(\"visibility\",Style.visibility)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("visibility")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"visibility" /*RemoteObject*/ )));
 BA.debugLineNum = 93;BA.debugLine="SetAttr(\"clip\",Style.clip)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("clip")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"clip" /*RemoteObject*/ )));
 BA.debugLineNum = 94;BA.debugLine="SetAttr(\"float\",Style.floatto)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("float")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"floatto" /*RemoteObject*/ )));
 BA.debugLineNum = 95;BA.debugLine="SetAttr(\"clear\",Style.clear)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("clear")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"clear" /*RemoteObject*/ )));
 BA.debugLineNum = 96;BA.debugLine="SetAttr(\"opacity\",Style.opacity)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("opacity")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"opacity" /*RemoteObject*/ )));
 BA.debugLineNum = 97;BA.debugLine="SetAttr(\"background\",Style.BackGround)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"BackGround" /*RemoteObject*/ )));
 BA.debugLineNum = 98;BA.debugLine="SetAttr(\"box-sizing\",Style.boxsizing)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("box-sizing")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"boxsizing" /*RemoteObject*/ )));
 BA.debugLineNum = 99;BA.debugLine="SetAttr(\"resize\",Style.resize)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("resize")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"resize" /*RemoteObject*/ )));
 BA.debugLineNum = 100;BA.debugLine="SetAttr(\"box-shadow\", Style.boxshadow)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("box-shadow")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"boxshadow" /*RemoteObject*/ )));
 BA.debugLineNum = 101;BA.debugLine="SetAttr(\"white-space\", Style.whitespace)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("white-space")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"whitespace" /*RemoteObject*/ )));
 BA.debugLineNum = 102;BA.debugLine="SetAttr(\"text-overflow\", Text.textoverflow)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-overflow")),(Object)(__ref.getField(false,"_text" /*RemoteObject*/ ).getField(true,"textoverflow" /*RemoteObject*/ )));
 BA.debugLineNum = 105;BA.debugLine="SetAttr(\"object-fit\", Image.objectfit)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("object-fit")),(Object)(__ref.getField(false,"_image" /*RemoteObject*/ ).getField(true,"objectfit" /*RemoteObject*/ )));
 BA.debugLineNum = 109;BA.debugLine="SetAttr(\"filter\",Filter.filter)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("filter")),(Object)(__ref.getField(false,"_filter" /*RemoteObject*/ ).getField(true,"Filter" /*RemoteObject*/ )));
 BA.debugLineNum = 110;BA.debugLine="SetAttr(\"-webkit-filter\", Filter.webkitfilter)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("-webkit-filter")),(Object)(__ref.getField(false,"_filter" /*RemoteObject*/ ).getField(true,"webkitfilter" /*RemoteObject*/ )));
 BA.debugLineNum = 113;BA.debugLine="SetAttr(\"animation\", Animation.animation)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"Animation" /*RemoteObject*/ )));
 BA.debugLineNum = 114;BA.debugLine="SetAttr(\"animation-delay\", Animation.delay)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-delay")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"delay" /*RemoteObject*/ )));
 BA.debugLineNum = 115;BA.debugLine="SetAttr(\"animation-direction\", Animation.directio";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-direction")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"direction" /*RemoteObject*/ )));
 BA.debugLineNum = 116;BA.debugLine="SetAttr(\"animation-duration\", Animation.duration)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-duration")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"duration" /*RemoteObject*/ )));
 BA.debugLineNum = 117;BA.debugLine="SetAttr(\"animation-fill-mode\", Animation.fillmode";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-fill-mode")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"fillmode" /*RemoteObject*/ )));
 BA.debugLineNum = 118;BA.debugLine="SetAttr(\"animation-iteration-count\", Animation.it";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-iteration-count")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"iterationcount" /*RemoteObject*/ )));
 BA.debugLineNum = 119;BA.debugLine="SetAttr(\"animation-name\", Animation.name)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-name")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"name" /*RemoteObject*/ )));
 BA.debugLineNum = 120;BA.debugLine="SetAttr(\"animation-play-state\", Animation.playsta";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-play-state")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"playstate" /*RemoteObject*/ )));
 BA.debugLineNum = 121;BA.debugLine="SetAttr(\"animation-timing-function\", Animation.ti";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("animation-timing-function")),(Object)(__ref.getField(false,"_animation" /*RemoteObject*/ ).getField(true,"timingfunction" /*RemoteObject*/ )));
 BA.debugLineNum = 125;BA.debugLine="SetAttr(\"-webkit-transition\",Transition.webkittra";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("-webkit-transition")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"webkittransition" /*RemoteObject*/ )));
 BA.debugLineNum = 126;BA.debugLine="SetAttr(\"transition\",Transition.transition)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transition")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"Transition" /*RemoteObject*/ )));
 BA.debugLineNum = 127;BA.debugLine="SetAttr(\"transition-delay\",Transition.delay)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transition-delay")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"delay" /*RemoteObject*/ )));
 BA.debugLineNum = 128;BA.debugLine="SetAttr(\"transition-duration\",Transition.duration";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transition-duration")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"duration" /*RemoteObject*/ )));
 BA.debugLineNum = 129;BA.debugLine="SetAttr(\"transition-property\",Transition.property";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transition-property")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"property" /*RemoteObject*/ )));
 BA.debugLineNum = 130;BA.debugLine="SetAttr(\"transition-timing-function\",Transition.t";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transition-timing-function")),(Object)(__ref.getField(false,"_transition" /*RemoteObject*/ ).getField(true,"timingfunction" /*RemoteObject*/ )));
 BA.debugLineNum = 133;BA.debugLine="SetAttr(\"text-transform\", Transform.texttransform";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("text-transform")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"texttransform" /*RemoteObject*/ )));
 BA.debugLineNum = 134;BA.debugLine="SetAttr(\"-ms-transform\", Transform.mstransform)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("-ms-transform")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"mstransform" /*RemoteObject*/ )));
 BA.debugLineNum = 135;BA.debugLine="SetAttr(\"transform-origin\", Transform.origin)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transform-origin")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"origin" /*RemoteObject*/ )));
 BA.debugLineNum = 136;BA.debugLine="SetAttr(\"transform-style\", Transform.style)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("transform-style")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"Style" /*RemoteObject*/ )));
 BA.debugLineNum = 137;BA.debugLine="SetAttr(\"perspective\", Transform.perspective)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("perspective")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"perspective" /*RemoteObject*/ )));
 BA.debugLineNum = 138;BA.debugLine="SetAttr(\"perspective-origin\", Transform.perspecti";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("perspective-origin")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"perspectiveorigin" /*RemoteObject*/ )));
 BA.debugLineNum = 139;BA.debugLine="SetAttr(\"backface-visibility\", Transform.backface";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("backface-visibility")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"backfacevisibility" /*RemoteObject*/ )));
 BA.debugLineNum = 140;BA.debugLine="SetAttr(\"-webkit-transform\", Transform.webkittran";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("-webkit-transform")),(Object)(__ref.getField(false,"_transform" /*RemoteObject*/ ).getField(true,"webkittransform" /*RemoteObject*/ )));
 BA.debugLineNum = 143;BA.debugLine="SetAttr(\"overflow\",Style.overflow.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("overflow")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"overflow" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 144;BA.debugLine="SetAttr(\"overflow-y\",Style.overflow.y)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("overflow-y")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"overflow" /*RemoteObject*/ ).getField(true,"y" /*RemoteObject*/ )));
 BA.debugLineNum = 145;BA.debugLine="SetAttr(\"overflow-x\",Style.overflow.x)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("overflow-x")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"overflow" /*RemoteObject*/ ).getField(true,"x" /*RemoteObject*/ )));
 BA.debugLineNum = 148;BA.debugLine="SetAttr(\"z-index\",Style.zindex)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("z-index")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(true,"zindex" /*RemoteObject*/ )));
 BA.debugLineNum = 149;BA.debugLine="SetAttr(\"position\",Style.position.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("position")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 150;BA.debugLine="SetAttr(\"left\",Style.position.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("left")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 151;BA.debugLine="SetAttr(\"top\",Style.position.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("top")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 152;BA.debugLine="SetAttr(\"bottom\",Style.position.bottom)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("bottom")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 153;BA.debugLine="SetAttr(\"right\",Style.position.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("right")),(Object)(__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 156;BA.debugLine="SetAttr(\"font\", Font.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 157;BA.debugLine="SetAttr(\"font-family\", Font.fontFamily)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-family")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"fontFamily" /*RemoteObject*/ )));
 BA.debugLineNum = 158;BA.debugLine="SetAttr(\"font-style\", Font.style)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-style")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"Style" /*RemoteObject*/ )));
 BA.debugLineNum = 159;BA.debugLine="SetAttr(\"font-size\", Font.size)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-size")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"size" /*RemoteObject*/ )));
 BA.debugLineNum = 160;BA.debugLine="SetAttr(\"font-weight\", Font.weight)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-weight")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"weight" /*RemoteObject*/ )));
 BA.debugLineNum = 161;BA.debugLine="SetAttr(\"font-variant\", Font.variant)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-variant")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"variant" /*RemoteObject*/ )));
 BA.debugLineNum = 162;BA.debugLine="SetAttr(\"src\", Font.src)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("src")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"src" /*RemoteObject*/ )));
 BA.debugLineNum = 163;BA.debugLine="SetAttr(\"font-stretch\", Font.stretch)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("font-stretch")),(Object)(__ref.getField(false,"_font" /*RemoteObject*/ ).getField(true,"stretch" /*RemoteObject*/ )));
 BA.debugLineNum = 165;BA.debugLine="SetAttr(\"list-style-type\", ListStyle.typeof)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("list-style-type")),(Object)(__ref.getField(false,"_liststyle" /*RemoteObject*/ ).getField(true,"typeOf" /*RemoteObject*/ )));
 BA.debugLineNum = 166;BA.debugLine="SetAttr(\"list-style-position\", ListStyle.position";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("list-style-position")),(Object)(__ref.getField(false,"_liststyle" /*RemoteObject*/ ).getField(true,"position" /*RemoteObject*/ )));
 BA.debugLineNum = 167;BA.debugLine="SetAttr(\"list-style-image\", $\"url('${ListStyle.im";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("list-style-image")),(Object)((RemoteObject.concat(RemoteObject.createImmutable("url('"),vmcss.__c.runMethod(true,"SmartStringFormatter",(Object)(BA.ObjectToString("")),(Object)((__ref.getField(false,"_liststyle" /*RemoteObject*/ ).getField(true,"Image" /*RemoteObject*/ )))),RemoteObject.createImmutable("')")))));
 BA.debugLineNum = 169;BA.debugLine="SetAttr(\"width\",Width.size)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("width")),(Object)(__ref.getField(false,"_width" /*RemoteObject*/ ).getField(true,"size" /*RemoteObject*/ )));
 BA.debugLineNum = 170;BA.debugLine="SetAttr(\"max-width\",Width.maxsize)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("max-width")),(Object)(__ref.getField(false,"_width" /*RemoteObject*/ ).getField(true,"maxsize" /*RemoteObject*/ )));
 BA.debugLineNum = 171;BA.debugLine="SetAttr(\"min-width\",Width.minsize)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("min-width")),(Object)(__ref.getField(false,"_width" /*RemoteObject*/ ).getField(true,"minsize" /*RemoteObject*/ )));
 BA.debugLineNum = 173;BA.debugLine="SetAttr(\"height\",Height.size)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("height")),(Object)(__ref.getField(false,"_height" /*RemoteObject*/ ).getField(true,"size" /*RemoteObject*/ )));
 BA.debugLineNum = 174;BA.debugLine="SetAttr(\"max-height\",Height.maxsize)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("max-height")),(Object)(__ref.getField(false,"_height" /*RemoteObject*/ ).getField(true,"maxsize" /*RemoteObject*/ )));
 BA.debugLineNum = 175;BA.debugLine="SetAttr(\"min-height\",Height.minsize)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("min-height")),(Object)(__ref.getField(false,"_height" /*RemoteObject*/ ).getField(true,"minsize" /*RemoteObject*/ )));
 BA.debugLineNum = 177;BA.debugLine="SetAttr(\"background-color\",BackGround.color)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-color")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"Color" /*RemoteObject*/ )));
 BA.debugLineNum = 178;BA.debugLine="SetAttr(\"background-image\", $\"url('${BackGround.i";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-image")),(Object)((RemoteObject.concat(RemoteObject.createImmutable("url('"),vmcss.__c.runMethod(true,"SmartStringFormatter",(Object)(BA.ObjectToString("")),(Object)((__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"Image" /*RemoteObject*/ )))),RemoteObject.createImmutable("')")))));
 BA.debugLineNum = 179;BA.debugLine="SetAttr(\"background-repeat\", BackGround.repeat)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-repeat")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"repeat" /*RemoteObject*/ )));
 BA.debugLineNum = 180;BA.debugLine="SetAttr(\"background-position\", BackGround.positio";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-position")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"position" /*RemoteObject*/ )));
 BA.debugLineNum = 181;BA.debugLine="SetAttr(\"background-attachment\", BackGround.attac";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-attachment")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"attachment" /*RemoteObject*/ )));
 BA.debugLineNum = 182;BA.debugLine="SetAttr(\"background-clip\", BackGround.clip)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-clip")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"clip" /*RemoteObject*/ )));
 BA.debugLineNum = 183;BA.debugLine="SetAttr(\"background-size\", BackGround.size)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-size")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"size" /*RemoteObject*/ )));
 BA.debugLineNum = 184;BA.debugLine="SetAttr(\"background-origin\", BackGround.origin)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("background-origin")),(Object)(__ref.getField(false,"_background" /*RemoteObject*/ ).getField(true,"Origin" /*RemoteObject*/ )));
 BA.debugLineNum = 187;BA.debugLine="SetAttr(\"border-collapse\",Border.collapse)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-collapse")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(true,"collapse" /*RemoteObject*/ )));
 BA.debugLineNum = 188;BA.debugLine="SetAttr(\"border-style\", Border.style.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-style")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 189;BA.debugLine="SetAttr(\"border-top-style\", Border.style.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-top-style")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 190;BA.debugLine="SetAttr(\"border-bottom-style\", Border.style.botto";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-bottom-style")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 191;BA.debugLine="SetAttr(\"border-right-style\", Border.style.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-right-style")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 192;BA.debugLine="SetAttr(\"border-left-style\", Border.style.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-left-style")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 194;BA.debugLine="SetAttr(\"border-color\", Border.color.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-color")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 195;BA.debugLine="SetAttr(\"border-left-color\", Border.color.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-left-color")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 196;BA.debugLine="SetAttr(\"border-right-color\", Border.color.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-right-color")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 197;BA.debugLine="SetAttr(\"border-top-color\", Border.color.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-top-color")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 198;BA.debugLine="SetAttr(\"border-bottom-color\", Border.color.botto";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-bottom-color")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 200;BA.debugLine="SetAttr(\"border-radius\", Border.radius.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-radius")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 201;BA.debugLine="SetAttr(\"border-top-left-radius\", Border.radius.t";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-top-left-radius")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).getField(true,"topleft" /*RemoteObject*/ )));
 BA.debugLineNum = 202;BA.debugLine="SetAttr(\"border-top-right-radius\", Border.radius.";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-top-right-radius")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).getField(true,"topright" /*RemoteObject*/ )));
 BA.debugLineNum = 203;BA.debugLine="SetAttr(\"border-bottom-left-radius\", Border.radiu";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-bottom-left-radius")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).getField(true,"bottomleft" /*RemoteObject*/ )));
 BA.debugLineNum = 204;BA.debugLine="SetAttr(\"border-bottom-right-radius\", Border.radi";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-bottom-right-radius")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).getField(true,"bottomright" /*RemoteObject*/ )));
 BA.debugLineNum = 207;BA.debugLine="SetAttr(\"border-width\", Border.width.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 208;BA.debugLine="SetAttr(\"border-left-width\",Border.width.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-left-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 209;BA.debugLine="SetAttr(\"border-right-width\",Border.width.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-right-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 210;BA.debugLine="SetAttr(\"border-top-width\",Border.width.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-top-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 211;BA.debugLine="SetAttr(\"border-bottom-width\",Border.width.bottom";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-bottom-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 214;BA.debugLine="SetAttr(\"border-image\", Border.image.image)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"Image" /*RemoteObject*/ )));
 BA.debugLineNum = 215;BA.debugLine="SetAttr(\"border-image-source\",Border.image.source";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image-source")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"source" /*RemoteObject*/ )));
 BA.debugLineNum = 216;BA.debugLine="SetAttr(\"border-image-slice\",Border.image.slice)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image-slice")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"slice" /*RemoteObject*/ )));
 BA.debugLineNum = 217;BA.debugLine="SetAttr(\"border-image-width\",Border.image.width)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image-width")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"Width" /*RemoteObject*/ )));
 BA.debugLineNum = 218;BA.debugLine="SetAttr(\"border-image-outset\",Border.image.outset";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image-outset")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"outset" /*RemoteObject*/ )));
 BA.debugLineNum = 219;BA.debugLine="SetAttr(\"border-image-repeat\",Border.image.repeat";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("border-image-repeat")),(Object)(__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).getField(true,"repeat" /*RemoteObject*/ )));
 BA.debugLineNum = 222;BA.debugLine="SetAttr(\"margin\",Margin.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("margin")),(Object)(__ref.getField(false,"_margin" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 223;BA.debugLine="SetAttr(\"margin-top\",Margin.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("margin-top")),(Object)(__ref.getField(false,"_margin" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 224;BA.debugLine="SetAttr(\"margin-bottom\",Margin.bottom)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("margin-bottom")),(Object)(__ref.getField(false,"_margin" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 225;BA.debugLine="SetAttr(\"margin-left\",Margin.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("margin-left")),(Object)(__ref.getField(false,"_margin" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 226;BA.debugLine="SetAttr(\"margin-right\",Margin.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("margin-right")),(Object)(__ref.getField(false,"_margin" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 228;BA.debugLine="SetAttr(\"padding\",Padding.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("padding")),(Object)(__ref.getField(false,"_padding" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 229;BA.debugLine="SetAttr(\"padding-top\",Padding.top)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("padding-top")),(Object)(__ref.getField(false,"_padding" /*RemoteObject*/ ).getField(true,"top" /*RemoteObject*/ )));
 BA.debugLineNum = 230;BA.debugLine="SetAttr(\"padding-bottom\",Padding.bottom)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("padding-bottom")),(Object)(__ref.getField(false,"_padding" /*RemoteObject*/ ).getField(true,"bottom" /*RemoteObject*/ )));
 BA.debugLineNum = 231;BA.debugLine="SetAttr(\"padding-left\",Padding.left)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("padding-left")),(Object)(__ref.getField(false,"_padding" /*RemoteObject*/ ).getField(true,"left" /*RemoteObject*/ )));
 BA.debugLineNum = 232;BA.debugLine="SetAttr(\"padding-right\",Padding.right)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("padding-right")),(Object)(__ref.getField(false,"_padding" /*RemoteObject*/ ).getField(true,"right" /*RemoteObject*/ )));
 BA.debugLineNum = 234;BA.debugLine="SetAttr(\"outline\",Outline.all)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("outline")),(Object)(__ref.getField(false,"_outline" /*RemoteObject*/ ).getField(true,"all" /*RemoteObject*/ )));
 BA.debugLineNum = 235;BA.debugLine="SetAttr(\"outline-style\",Outline.style)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("outline-style")),(Object)(__ref.getField(false,"_outline" /*RemoteObject*/ ).getField(true,"Style" /*RemoteObject*/ )));
 BA.debugLineNum = 236;BA.debugLine="SetAttr(\"outline-offset\",Outline.offset)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("outline-offset")),(Object)(__ref.getField(false,"_outline" /*RemoteObject*/ ).getField(true,"offset" /*RemoteObject*/ )));
 BA.debugLineNum = 237;BA.debugLine="SetAttr(\"outline-width\",Outline.width)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("outline-width")),(Object)(__ref.getField(false,"_outline" /*RemoteObject*/ ).getField(true,"Width" /*RemoteObject*/ )));
 BA.debugLineNum = 238;BA.debugLine="SetAttr(\"outline-color\",Outline.color)";
Debug.JustUpdateDeviceLine();
__ref.runClassMethod (b4j.example.vmcss.class, "_setattr" /*RemoteObject*/ ,(Object)(BA.ObjectToString("outline-color")),(Object)(__ref.getField(false,"_outline" /*RemoteObject*/ ).getField(true,"Color" /*RemoteObject*/ )));
 BA.debugLineNum = 241;BA.debugLine="sortit.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_sortit" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 242;BA.debugLine="For Each strProp As String In css.Keys";
Debug.JustUpdateDeviceLine();
{
final RemoteObject group126 = __ref.getField(false,"_css" /*RemoteObject*/ ).runMethod(false,"Keys");
final int groupLen126 = group126.runMethod(true,"getSize").<Integer>get()
;int index126 = 0;
;
for (; index126 < groupLen126;index126++){
_strprop = BA.ObjectToString(group126.runMethod(false,"Get",index126));Debug.locals.put("strProp", _strprop);
Debug.locals.put("strProp", _strprop);
 BA.debugLineNum = 243;BA.debugLine="sortit.Add(strProp)";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_sortit" /*RemoteObject*/ ).runVoidMethod ("Add",(Object)((_strprop)));
 }
}Debug.locals.put("strProp", _strprop);
;
 BA.debugLineNum = 245;BA.debugLine="sortit.Sort(True)";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_sortit" /*RemoteObject*/ ).runVoidMethod ("Sort",(Object)(vmcss.__c.getField(true,"True")));
 BA.debugLineNum = 246;BA.debugLine="End Sub";
Debug.JustUpdateDeviceLine();
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _class_globals(RemoteObject __ref) throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Class_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Type CssOverflow(all As String,x As String,y As S";
;
 //BA.debugLineNum = 4;BA.debugLine="Type StyleObj(letterspacing As String, Color As S";
;
 //BA.debugLineNum = 8;BA.debugLine="Type CssSize(size As String, maxsize As String,mi";
;
 //BA.debugLineNum = 9;BA.debugLine="Type CssBackground(Color As String,Image As Strin";
;
 //BA.debugLineNum = 10;BA.debugLine="Type CssPositions(all As String, top As String,bo";
;
 //BA.debugLineNum = 11;BA.debugLine="Type CssRadius(all As String, topleft As String,t";
;
 //BA.debugLineNum = 12;BA.debugLine="Type CssBorder(Style As CssPositions,size As Stri";
;
 //BA.debugLineNum = 13;BA.debugLine="Type CssOutline(all As String,offset As String,Co";
;
 //BA.debugLineNum = 14;BA.debugLine="Type CssFont(all As String,fontFamily As String,S";
;
 //BA.debugLineNum = 15;BA.debugLine="Type CssBorderImage(Image As String,source As Str";
;
 //BA.debugLineNum = 16;BA.debugLine="Type CssListStyle(typeOf As String,position As St";
;
 //BA.debugLineNum = 17;BA.debugLine="Type CssTransform(texttransform As String, mstran";
;
 //BA.debugLineNum = 18;BA.debugLine="Type CssTransition(webkittransition As String,Tra";
;
 //BA.debugLineNum = 19;BA.debugLine="Type CssAnimation(Animation As String,delay As St";
;
 //BA.debugLineNum = 20;BA.debugLine="Type CssFilter(Filter As String,webkitfilter As S";
;
 //BA.debugLineNum = 21;BA.debugLine="Type CssImage(objectfit As String)";
;
 //BA.debugLineNum = 22;BA.debugLine="Type CssText(align As String,decoration As String";
;
 //BA.debugLineNum = 23;BA.debugLine="Public Style As StyleObj";
vmcss._style = RemoteObject.createNew ("b4j.example.vmcss._styleobj");__ref.setField("_style",vmcss._style);
 //BA.debugLineNum = 24;BA.debugLine="Public Width As CssSize";
vmcss._width = RemoteObject.createNew ("b4j.example.vmcss._csssize");__ref.setField("_width",vmcss._width);
 //BA.debugLineNum = 25;BA.debugLine="Public Height As CssSize";
vmcss._height = RemoteObject.createNew ("b4j.example.vmcss._csssize");__ref.setField("_height",vmcss._height);
 //BA.debugLineNum = 26;BA.debugLine="Public BackGround As CssBackground";
vmcss._background = RemoteObject.createNew ("b4j.example.vmcss._cssbackground");__ref.setField("_background",vmcss._background);
 //BA.debugLineNum = 27;BA.debugLine="Public Border As CssBorder";
vmcss._border = RemoteObject.createNew ("b4j.example.vmcss._cssborder");__ref.setField("_border",vmcss._border);
 //BA.debugLineNum = 28;BA.debugLine="Public Margin As CssPositions";
vmcss._margin = RemoteObject.createNew ("b4j.example.vmcss._csspositions");__ref.setField("_margin",vmcss._margin);
 //BA.debugLineNum = 29;BA.debugLine="Public Padding As CssPositions";
vmcss._padding = RemoteObject.createNew ("b4j.example.vmcss._csspositions");__ref.setField("_padding",vmcss._padding);
 //BA.debugLineNum = 30;BA.debugLine="Public Outline As CssOutline";
vmcss._outline = RemoteObject.createNew ("b4j.example.vmcss._cssoutline");__ref.setField("_outline",vmcss._outline);
 //BA.debugLineNum = 31;BA.debugLine="Public Text As CssText";
vmcss._text = RemoteObject.createNew ("b4j.example.vmcss._csstext");__ref.setField("_text",vmcss._text);
 //BA.debugLineNum = 32;BA.debugLine="Public Font As CssFont";
vmcss._font = RemoteObject.createNew ("b4j.example.vmcss._cssfont");__ref.setField("_font",vmcss._font);
 //BA.debugLineNum = 33;BA.debugLine="Private css As Map";
vmcss._css = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");__ref.setField("_css",vmcss._css);
 //BA.debugLineNum = 34;BA.debugLine="Public ListStyle As CssListStyle";
vmcss._liststyle = RemoteObject.createNew ("b4j.example.vmcss._cssliststyle");__ref.setField("_liststyle",vmcss._liststyle);
 //BA.debugLineNum = 35;BA.debugLine="Public Transform As CssTransform";
vmcss._transform = RemoteObject.createNew ("b4j.example.vmcss._csstransform");__ref.setField("_transform",vmcss._transform);
 //BA.debugLineNum = 36;BA.debugLine="Public Transition As CssTransition";
vmcss._transition = RemoteObject.createNew ("b4j.example.vmcss._csstransition");__ref.setField("_transition",vmcss._transition);
 //BA.debugLineNum = 37;BA.debugLine="Public Animation As CssAnimation";
vmcss._animation = RemoteObject.createNew ("b4j.example.vmcss._cssanimation");__ref.setField("_animation",vmcss._animation);
 //BA.debugLineNum = 38;BA.debugLine="Public Filter As CssFilter";
vmcss._filter = RemoteObject.createNew ("b4j.example.vmcss._cssfilter");__ref.setField("_filter",vmcss._filter);
 //BA.debugLineNum = 39;BA.debugLine="Public Image As CssImage";
vmcss._image = RemoteObject.createNew ("b4j.example.vmcss._cssimage");__ref.setField("_image",vmcss._image);
 //BA.debugLineNum = 40;BA.debugLine="Private sortit As List";
vmcss._sortit = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.List");__ref.setField("_sortit",vmcss._sortit);
 //BA.debugLineNum = 41;BA.debugLine="Private BANano As BANano   'ignore";
vmcss._banano = RemoteObject.createNew ("com.ab.banano.BANano");__ref.setField("_banano",vmcss._banano);
 //BA.debugLineNum = 42;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _initialize(RemoteObject __ref,RemoteObject _ba) throws Exception{
try {
		Debug.PushSubsStack("Initialize (vmcss) ","vmcss",48,__ref.getField(false, "ba"),__ref,45);
if (RapidSub.canDelegate("initialize")) { return __ref.runUserSub(false, "vmcss","initialize", __ref, _ba);}
__ref.runVoidMethodAndSync("innerInitializeHelper", _ba);
Debug.locals.put("ba", _ba);
 BA.debugLineNum = 45;BA.debugLine="Public Sub Initialize";
Debug.JustUpdateDeviceLine();
 BA.debugLineNum = 46;BA.debugLine="css.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_css" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 47;BA.debugLine="BackGround.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_background" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 48;BA.debugLine="Border.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 49;BA.debugLine="Border.Color.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Color" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 50;BA.debugLine="Border.width.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Width" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 51;BA.debugLine="Border.style.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Style" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 52;BA.debugLine="Border.radius.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"radius" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 53;BA.debugLine="Border.image.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_border" /*RemoteObject*/ ).getField(false,"Image" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 54;BA.debugLine="Margin.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_margin" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 55;BA.debugLine="Padding.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_padding" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 56;BA.debugLine="Height.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_height" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 57;BA.debugLine="Width.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_width" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 58;BA.debugLine="Outline.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_outline" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 59;BA.debugLine="Style.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_style" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 60;BA.debugLine="Text.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_text" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 61;BA.debugLine="Style.position.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"position" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 62;BA.debugLine="Style.overflow.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_style" /*RemoteObject*/ ).getField(false,"overflow" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 63;BA.debugLine="Font.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_font" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 64;BA.debugLine="ListStyle.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_liststyle" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 65;BA.debugLine="Transform.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_transform" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 66;BA.debugLine="Transition.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_transition" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 67;BA.debugLine="Animation.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_animation" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 68;BA.debugLine="Filter.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_filter" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 69;BA.debugLine="Image.Initialize";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_image" /*RemoteObject*/ ).runVoidMethod ("Initialize");
 BA.debugLineNum = 70;BA.debugLine="End Sub";
Debug.JustUpdateDeviceLine();
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _setattr(RemoteObject __ref,RemoteObject _property,RemoteObject _value) throws Exception{
try {
		Debug.PushSubsStack("SetAttr (vmcss) ","vmcss",48,__ref.getField(false, "ba"),__ref,72);
if (RapidSub.canDelegate("setattr")) { return __ref.runUserSub(false, "vmcss","setattr", __ref, _property, _value);}
Debug.locals.put("property", _property);
Debug.locals.put("value", _value);
 BA.debugLineNum = 72;BA.debugLine="Sub SetAttr(property As String,value As String) As";
Debug.JustUpdateDeviceLine();
 BA.debugLineNum = 73;BA.debugLine="value = value.Trim";
Debug.JustUpdateDeviceLine();
_value = _value.runMethod(true,"trim");Debug.locals.put("value", _value);
 BA.debugLineNum = 74;BA.debugLine="If value.Length > 0 Then";
Debug.JustUpdateDeviceLine();
if (RemoteObject.solveBoolean(">",_value.runMethod(true,"length"),BA.numberCast(double.class, 0))) { 
 BA.debugLineNum = 75;BA.debugLine="css.Put(property,value)";
Debug.JustUpdateDeviceLine();
__ref.getField(false,"_css" /*RemoteObject*/ ).runVoidMethod ("Put",(Object)((_property)),(Object)((_value)));
 };
 BA.debugLineNum = 77;BA.debugLine="Return Me";
Debug.JustUpdateDeviceLine();
if (true) return (__ref);
 BA.debugLineNum = 78;BA.debugLine="End Sub";
Debug.JustUpdateDeviceLine();
return RemoteObject.createImmutable(null);
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _tojson(RemoteObject __ref) throws Exception{
try {
		Debug.PushSubsStack("ToJSON (vmcss) ","vmcss",48,__ref.getField(false, "ba"),__ref,254);
if (RapidSub.canDelegate("tojson")) { return __ref.runUserSub(false, "vmcss","tojson", __ref);}
RemoteObject _sjson = RemoteObject.createImmutable("");
 BA.debugLineNum = 254;BA.debugLine="Sub ToJSON As String";
Debug.JustUpdateDeviceLine();
 BA.debugLineNum = 255;BA.debugLine="Dim sjson As String = BANano.ToJson(css)";
Debug.JustUpdateDeviceLine();
_sjson = BA.ObjectToString(__ref.getField(false,"_banano" /*RemoteObject*/ ).runMethod(false,"ToJson",(Object)((__ref.getField(false,"_css" /*RemoteObject*/ ).getObject()))));Debug.locals.put("sjson", _sjson);Debug.locals.put("sjson", _sjson);
 BA.debugLineNum = 256;BA.debugLine="Return sjson";
Debug.JustUpdateDeviceLine();
if (true) return _sjson;
 BA.debugLineNum = 257;BA.debugLine="End Sub";
Debug.JustUpdateDeviceLine();
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _tomap(RemoteObject __ref) throws Exception{
try {
		Debug.PushSubsStack("ToMap (vmcss) ","vmcss",48,__ref.getField(false, "ba"),__ref,249);
if (RapidSub.canDelegate("tomap")) { return __ref.runUserSub(false, "vmcss","tomap", __ref);}
 BA.debugLineNum = 249;BA.debugLine="Sub ToMap As Map";
Debug.JustUpdateDeviceLine();
 BA.debugLineNum = 250;BA.debugLine="Return css";
Debug.JustUpdateDeviceLine();
if (true) return __ref.getField(false,"_css" /*RemoteObject*/ );
 BA.debugLineNum = 251;BA.debugLine="End Sub";
Debug.JustUpdateDeviceLine();
return RemoteObject.createImmutable(null);
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
}