
package b4j.example;

import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RemoteObject;

public class vminputcontrol {
    public static RemoteObject myClass;
	public vminputcontrol() {
	}
    public static PCBA staticBA = new PCBA(null, vminputcontrol.class);

public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _name = RemoteObject.createImmutable("");
public static RemoteObject _label = RemoteObject.createImmutable("");
public static RemoteObject _typeof = RemoteObject.createImmutable("");
public static RemoteObject _helpertext = RemoteObject.createImmutable("");
public static RemoteObject _errortext = RemoteObject.createImmutable("");
public static RemoteObject _required = RemoteObject.createImmutable(false);
public static RemoteObject _clearable = RemoteObject.createImmutable(false);
public static RemoteObject _sourcetable = RemoteObject.createImmutable("");
public static RemoteObject _sourcefield = RemoteObject.createImmutable("");
public static RemoteObject _displayfield = RemoteObject.createImmutable("");
public static RemoteObject _fieldtype = RemoteObject.createImmutable("");
public static RemoteObject _isvisible = RemoteObject.createImmutable(false);
public static RemoteObject _defaultvalue = RemoteObject.declareNull("Object");
public static RemoteObject _options = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
public static RemoteObject _minvalue = RemoteObject.createImmutable(0);
public static RemoteObject _maxvalue = RemoteObject.createImmutable(0);
public static RemoteObject _module = RemoteObject.declareNull("Object");
public static RemoteObject _methodname = RemoteObject.createImmutable("");
public static RemoteObject _iconname = RemoteObject.createImmutable("");
public static RemoteObject _isprimary = RemoteObject.createImmutable(false);
public static RemoteObject _isaccent = RemoteObject.createImmutable(false);
public static RemoteObject _isdisabled = RemoteObject.createImmutable(false);
public static RemoteObject _text = RemoteObject.createImmutable("");
public static RemoteObject _description = RemoteObject.createImmutable("");
public static RemoteObject _thirdline = RemoteObject.createImmutable("");
public static RemoteObject _lines = RemoteObject.createImmutable(0);
public static RemoteObject _key = RemoteObject.createImmutable("");
public static RemoteObject _source = RemoteObject.createImmutable("");
public static RemoteObject _actionicon = RemoteObject.createImmutable("");
public static RemoteObject _menuicon = RemoteObject.createImmutable("");
public static RemoteObject _menuclick = RemoteObject.createImmutable(false);
public static RemoteObject _addedit = RemoteObject.createImmutable(false);
public static RemoteObject _editmethod = RemoteObject.createImmutable("");
public static RemoteObject _deletemethod = RemoteObject.createImmutable("");
public static RemoteObject _editcaption = RemoteObject.createImmutable("");
public static RemoteObject _deletecaption = RemoteObject.createImmutable("");
public static RemoteObject _row = RemoteObject.createImmutable("");
public static RemoteObject _cell = RemoteObject.createImmutable("");
public static RemoteObject _offsetsmall = RemoteObject.createImmutable("");
public static RemoteObject _offsetmedium = RemoteObject.createImmutable("");
public static RemoteObject _offsetlarge = RemoteObject.createImmutable("");
public static RemoteObject _offsetxlarge = RemoteObject.createImmutable("");
public static RemoteObject _sizesmall = RemoteObject.createImmutable("");
public static RemoteObject _sizemedium = RemoteObject.createImmutable("");
public static RemoteObject _sizelarge = RemoteObject.createImmutable("");
public static RemoteObject _sizexlarge = RemoteObject.createImmutable("");
public static RemoteObject _visibility = RemoteObject.createImmutable("");
public static RemoteObject _useoptions = RemoteObject.createImmutable(false);
public static RemoteObject _multiple = RemoteObject.createImmutable(false);
public static RemoteObject _margintop = RemoteObject.declareNull("Object");
public static RemoteObject _marginbottom = RemoteObject.declareNull("Object");
public static RemoteObject _marginleft = RemoteObject.declareNull("Object");
public static RemoteObject _marginright = RemoteObject.declareNull("Object");
public static RemoteObject _paddingtop = RemoteObject.declareNull("Object");
public static RemoteObject _paddingbottom = RemoteObject.declareNull("Object");
public static RemoteObject _paddingleft = RemoteObject.declareNull("Object");
public static RemoteObject _paddingright = RemoteObject.declareNull("Object");
public static RemoteObject _optionslist = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _maxlength = RemoteObject.declareNull("Object");
public static RemoteObject _tabindex = RemoteObject.createImmutable(0);
public static RemoteObject _autogrow = RemoteObject.createImmutable(false);
public static RemoteObject _openonfocus = RemoteObject.createImmutable(false);
public static RemoteObject _immediately = RemoteObject.createImmutable(false);
public static RemoteObject _placeholder = RemoteObject.createImmutable("");
public static RemoteObject _thumblabel = RemoteObject.createImmutable(false);
public static RemoteObject _dense = RemoteObject.createImmutable(false);
public static RemoteObject _iconsize = RemoteObject.createImmutable("");
public static RemoteObject _raised = RemoteObject.createImmutable(false);
public static RemoteObject _ripple = RemoteObject.createImmutable(false);
public static RemoteObject _fitwidth = RemoteObject.createImmutable(false);
public static RemoteObject _href = RemoteObject.createImmutable("");
public static RemoteObject _menutrigger = RemoteObject.createImmutable(false);
public static RemoteObject _iconbutton = RemoteObject.createImmutable(false);
public static RemoteObject _plain = RemoteObject.createImmutable(false);
public static RemoteObject _mini = RemoteObject.createImmutable(false);
public static RemoteObject _fab = RemoteObject.createImmutable(false);
public static RemoteObject _listaction = RemoteObject.createImmutable(false);
public static RemoteObject _buttontype = RemoteObject.createImmutable("");
public static RemoteObject _navigateto = RemoteObject.createImmutable("");
public static RemoteObject _fabposition = RemoteObject.createImmutable("");
public static RemoteObject _fabfixed = RemoteObject.createImmutable(false);
public static RemoteObject _tag = RemoteObject.createImmutable("");
public static RemoteObject _width = RemoteObject.createImmutable("");
public static RemoteObject _height = RemoteObject.createImmutable("");
public static RemoteObject _isround = RemoteObject.createImmutable(false);
public static RemoteObject _alt = RemoteObject.createImmutable("");
public static RemoteObject _count = RemoteObject.createImmutable("");
public static RemoteObject _start = RemoteObject.createImmutable("");
public static RemoteObject _finish = RemoteObject.createImmutable("");
public static RemoteObject _speed = RemoteObject.createImmutable("");
public static RemoteObject _refreshinterval = RemoteObject.createImmutable("");
public static RemoteObject _boxtype = RemoteObject.createImmutable("");
public static RemoteObject _iconcolor = RemoteObject.createImmutable("");
public static RemoteObject _iconbackgroundcolor = RemoteObject.createImmutable("");
public static RemoteObject _hoverzoomeffect = RemoteObject.createImmutable(false);
public static RemoteObject _hoverexpandeffect = RemoteObject.createImmutable(false);
public static RemoteObject _bsetcounter = RemoteObject.createImmutable(false);
public static RemoteObject _clickable = RemoteObject.createImmutable(false);
public static RemoteObject _deletable = RemoteObject.createImmutable(false);
public static RemoteObject _thelimit = RemoteObject.createImmutable("");
public static RemoteObject _checkduplicates = RemoteObject.createImmutable(false);
public static RemoteObject _inputtype = RemoteObject.createImmutable("");
public static RemoteObject _static = RemoteObject.createImmutable(false);
public static RemoteObject _footer = RemoteObject.createImmutable(false);
public static RemoteObject _format = RemoteObject.createImmutable("");
public static RemoteObject _locale = RemoteObject.createImmutable("");
public static RemoteObject _modal = RemoteObject.createImmutable(false);
public static RemoteObject _size = RemoteObject.createImmutable("");
public static RemoteObject _value = RemoteObject.createImmutable("");
public static RemoteObject _showothermonths = RemoteObject.createImmutable(false);
public static RemoteObject _calendarweeks = RemoteObject.createImmutable(false);
public static RemoteObject _header = RemoteObject.createImmutable(false);
public static RemoteObject _mode = RemoteObject.createImmutable("");
public static RemoteObject _readonly = RemoteObject.createImmutable(false);
public static RemoteObject _usedatasource = RemoteObject.createImmutable(false);
public static RemoteObject _togglepassword = RemoteObject.createImmutable(false);
public static RemoteObject _exclude = RemoteObject.createImmutable(false);
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moddashboard _moddashboard = null;
public static b4j.example.modexpenses _modexpenses = null;
public static b4j.example.modstats _modstats = null;
public static b4j.example.modexpensetypes _modexpensetypes = null;
public static b4j.example.modexpensecategories _modexpensecategories = null;
public static Object[] GetGlobals(RemoteObject _ref) throws Exception {
		return new Object[] {"ActionIcon",_ref.getField(false, "_actionicon"),"AddEdit",_ref.getField(false, "_addedit"),"Alt",_ref.getField(false, "_alt"),"AutoGrow",_ref.getField(false, "_autogrow"),"BoxType",_ref.getField(false, "_boxtype"),"bSetCounter",_ref.getField(false, "_bsetcounter"),"ButtonType",_ref.getField(false, "_buttontype"),"CalendarWeeks",_ref.getField(false, "_calendarweeks"),"cell",_ref.getField(false, "_cell"),"CheckDuplicates",_ref.getField(false, "_checkduplicates"),"clearable",_ref.getField(false, "_clearable"),"Clickable",_ref.getField(false, "_clickable"),"Count",_ref.getField(false, "_count"),"defaultValue",_ref.getField(false, "_defaultvalue"),"Deletable",_ref.getField(false, "_deletable"),"DeleteCaption",_ref.getField(false, "_deletecaption"),"DeleteMethod",_ref.getField(false, "_deletemethod"),"Dense",_ref.getField(false, "_dense"),"Description",_ref.getField(false, "_description"),"displayField",_ref.getField(false, "_displayfield"),"EditCaption",_ref.getField(false, "_editcaption"),"EditMethod",_ref.getField(false, "_editmethod"),"errorText",_ref.getField(false, "_errortext"),"Exclude",_ref.getField(false, "_exclude"),"Fab",_ref.getField(false, "_fab"),"FabFixed",_ref.getField(false, "_fabfixed"),"FabPosition",_ref.getField(false, "_fabposition"),"fieldType",_ref.getField(false, "_fieldtype"),"Finish",_ref.getField(false, "_finish"),"FitWidth",_ref.getField(false, "_fitwidth"),"Footer",_ref.getField(false, "_footer"),"Format",_ref.getField(false, "_format"),"Header",_ref.getField(false, "_header"),"Height",_ref.getField(false, "_height"),"helperText",_ref.getField(false, "_helpertext"),"HoverExpandEffect",_ref.getField(false, "_hoverexpandeffect"),"HoverZoomEffect",_ref.getField(false, "_hoverzoomeffect"),"href",_ref.getField(false, "_href"),"IconBackgroundColor",_ref.getField(false, "_iconbackgroundcolor"),"IconButton",_ref.getField(false, "_iconbutton"),"IconColor",_ref.getField(false, "_iconcolor"),"IconName",_ref.getField(false, "_iconname"),"IconSize",_ref.getField(false, "_iconsize"),"immediately",_ref.getField(false, "_immediately"),"InputType",_ref.getField(false, "_inputtype"),"IsAccent",_ref.getField(false, "_isaccent"),"IsDisabled",_ref.getField(false, "_isdisabled"),"IsPrimary",_ref.getField(false, "_isprimary"),"IsRound",_ref.getField(false, "_isround"),"Isvisible",_ref.getField(false, "_isvisible"),"Key",_ref.getField(false, "_key"),"label",_ref.getField(false, "_label"),"Lines",_ref.getField(false, "_lines"),"ListAction",_ref.getField(false, "_listaction"),"Locale",_ref.getField(false, "_locale"),"MarginBottom",_ref.getField(false, "_marginbottom"),"MarginLeft",_ref.getField(false, "_marginleft"),"MarginRight",_ref.getField(false, "_marginright"),"MarginTop",_ref.getField(false, "_margintop"),"MaxLength",_ref.getField(false, "_maxlength"),"MaxValue",_ref.getField(false, "_maxvalue"),"MenuClick",_ref.getField(false, "_menuclick"),"MenuIcon",_ref.getField(false, "_menuicon"),"MenuTrigger",_ref.getField(false, "_menutrigger"),"methodName",_ref.getField(false, "_methodname"),"Mini",_ref.getField(false, "_mini"),"MinValue",_ref.getField(false, "_minvalue"),"Modal",_ref.getField(false, "_modal"),"Mode",_ref.getField(false, "_mode"),"module",_ref.getField(false, "_module"),"multiple",_ref.getField(false, "_multiple"),"name",_ref.getField(false, "_name"),"NavigateTo",_ref.getField(false, "_navigateto"),"OffsetLarge",_ref.getField(false, "_offsetlarge"),"OffsetMedium",_ref.getField(false, "_offsetmedium"),"OffsetSmall",_ref.getField(false, "_offsetsmall"),"OffsetXLarge",_ref.getField(false, "_offsetxlarge"),"openonfocus",_ref.getField(false, "_openonfocus"),"options",_ref.getField(false, "_options"),"OptionsList",_ref.getField(false, "_optionslist"),"PaddingBottom",_ref.getField(false, "_paddingbottom"),"PaddingLeft",_ref.getField(false, "_paddingleft"),"PaddingRight",_ref.getField(false, "_paddingright"),"PaddingTop",_ref.getField(false, "_paddingtop"),"PlaceHolder",_ref.getField(false, "_placeholder"),"Plain",_ref.getField(false, "_plain"),"Raised",_ref.getField(false, "_raised"),"readonly",_ref.getField(false, "_readonly"),"RefreshInterval",_ref.getField(false, "_refreshinterval"),"Required",_ref.getField(false, "_required"),"Ripple",_ref.getField(false, "_ripple"),"Row",_ref.getField(false, "_row"),"ShowOtherMonths",_ref.getField(false, "_showothermonths"),"Size",_ref.getField(false, "_size"),"SizeLarge",_ref.getField(false, "_sizelarge"),"SizeMedium",_ref.getField(false, "_sizemedium"),"SizeSmall",_ref.getField(false, "_sizesmall"),"SizeXLarge",_ref.getField(false, "_sizexlarge"),"Source",_ref.getField(false, "_source"),"sourceField",_ref.getField(false, "_sourcefield"),"sourceTable",_ref.getField(false, "_sourcetable"),"Speed",_ref.getField(false, "_speed"),"Start",_ref.getField(false, "_start"),"Static",_ref.getField(false, "_static"),"TabIndex",_ref.getField(false, "_tabindex"),"Tag",_ref.getField(false, "_tag"),"Text",_ref.getField(false, "_text"),"TheLimit",_ref.getField(false, "_thelimit"),"ThirdLine",_ref.getField(false, "_thirdline"),"ThumbLabel",_ref.getField(false, "_thumblabel"),"TogglePassword",_ref.getField(false, "_togglepassword"),"typeOf",_ref.getField(false, "_typeof"),"UseDataSource",_ref.getField(false, "_usedatasource"),"UseOptions",_ref.getField(false, "_useoptions"),"Value",_ref.getField(false, "_value"),"Visibility",_ref.getField(false, "_visibility"),"Width",_ref.getField(false, "_width")};
}
}